# Generated by Django 3.2.9 on 2021-12-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Martialsts', models.CharField(max_length=200)),
            ],
        ),
    ]
