# Generated by Django 3.2.9 on 2021-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='Gender',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='Martialsts',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='Phone',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='pincode',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
